"""Prometheus metrics definitions for Moonshot-CEX."""
from prometheus_client import Counter, Gauge, Histogram

cycle_duration = Histogram(
    "moonshot_cycle_duration_seconds",
    "Duration of one trading cycle in seconds",
    buckets=[1, 5, 10, 30, 60, 120],
)

signals_generated = Counter(
    "moonshot_signals_generated_total",
    "Total signals generated by agents",
    ["agent"],
)

decisions_made = Counter(
    "moonshot_decisions_made_total",
    "Total Bayesian decisions made",
    ["outcome"],
)

active_positions = Gauge(
    "moonshot_active_positions",
    "Number of currently open positions",
)

trades_total = Counter(
    "moonshot_trades_total",
    "Total trades executed",
    ["side", "exchange"],
)

account_equity = Gauge(
    "moonshot_account_equity_usd",
    "Current account equity in USD",
)

portfolio_value = Gauge(
    "moonshot_portfolio_value_usd",
    "Total portfolio value including open positions",
)

current_drawdown = Gauge(
    "moonshot_current_drawdown",
    "Current drawdown from peak equity (0.0-1.0)",
)

win_rate = Gauge(
    "moonshot_win_rate",
    "Rolling win rate over last 50 trades",
)

avg_r_multiple = Gauge(
    "moonshot_avg_r_multiple",
    "Average R-multiple over last 50 trades",
)

api_latency = Histogram(
    "moonshot_api_latency_seconds",
    "Exchange API call latency",
    ["exchange", "endpoint"],
    buckets=[0.1, 0.25, 0.5, 1.0, 2.0, 5.0, 10.0],
)

errors_total = Counter(
    "moonshot_errors_total",
    "Total errors by component and type",
    ["component", "error_type"],
)
